### ISSUE TITLE
Simplify intent creation with inline syntax.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#32]
It would be nice to NOT to require the usage of CONV_INTENT, NON_CONV_INTENT, TERM, AND/OR/NOR/etc. when creating at least the simple intents. Indeed, consider this code snippet from Alarm Clock example:
```java
solver.addIntent(
    new NON_CONV_INTENT(
        "id",
        new TERM("id == x:alarm", 1, 1), // Term #1 (index=0).
        new TERM(                        // Term #2 (index=1).
            new AND("id == nlp:num", "~NUM_UNITTYPE == datetime", "~NUM_ISEQUALCONDITION == true"),
            0,
            7 // Up to 7 numeric `datetime` units.
        )
    ),
    this::onMatch
);
```

This could be easily replaced with a simpler and clearer version:
```java
solver.addConvIntent("
     id, 
     {id == x:alarm, 1, 1},
     {id == nlp:num && ~NUM_UNITTYPE == datetime && ~NUM_ISEQUALCONDITION == true, 0, 7}",
     this::onMatch   
 );
```

**Comment by syermakov** [comment]
How about the following concept?

1) Use DSL to describe intents
2) Use annotations to specify which method should be invoked upon match
3) Use annotations on method parameters to simplify extraction of meta-data from tokens

Basic example:
```java
public class AlarmModel {
    @Intent(""
        + "ordered exact match "
        + "  [id = 'x:alarm'],"
        + "  my_time:[id == 'nlp:num' && NUM_UNIT_TYPE == 'datetime' && NUM_FROM == NUM_TO] "
        + "")
    public NCQueryResult setupAlarm(
        @Slot("my_time.NUM_FROM") long numValue,
        @Slot("my_time.NUM_UNIT_TYPE") ChronoUnit numUnit
    ) {
        
        // ... do something ...
        
        return NCQueryResult.text("...");
    }
}
```

Key aspects of DSL:

 - Starts with matching options (ordered vs unordered, exact vs non-exact match, etc)
 - Terms are described as a comma-separated list of '[...]' blocks where each block contains a mix of and/or conditions to match on token meta-data  
 - Each term can have an optional alias (`my_time` in the example above) in order to simplify access to tokens and meta-data attributes
 - Use regexp-like quantifiers for terms (f.e. `[...]+`, `[...]?`, `[...]*`, `[...]{0,7}`, etc)
 - If needed, we can support externalization of intent definition to model.json file and reference it by some ID, instead of inlining into the annotation
  
Key aspects of annotated methods:

- Allow to specify the following parameters without any annotations:
  - `NCIntentSolverContext`
  - `NCQueryContext`
  - `NCConversationContext`
  - `NCSentence`
  - ...probably some more
- Allow to reference tokens by term alias:
  - `@Slot("my_time") NCToken` for single token
  - `@Slot("my_time") List<NCToken>` for multiple tokens
- Allow to reference meta-data attributes by term alias using some notation like `<term_alias>.<metadata_key>`:
  - `@Slot("my_time.NUM_FROM") long numValue` for single token (where `NUM_FROM` is a meta-data key)
  - `@Slot("my_time.NUM_FROM") List<Long> numValues` for multiple tokens 
- For optional terms (min quantifier = 0) we can use `null` values or wrap with `java.util.Optional`
- Support automatic conversion of common types (f.e. `long -> Instant`, `string -> ChronoUnit`, etc)

A slightly more complicated example:
```java
public class AlarmModel {
    @Intent(""
        + "unordered exact match "
        + "  [id = 'x:alarm'],"
        + "  my_time:["
        + "    (id == 'nlp:num' && NUM_UNIT_TYPE == 'datetime' && NUM_FROM == NUM_TO)"
        + "    || "
        + "    (id == 'nlp:date' && DATE_FROM == DATE_TO)"
        + "  ]+ " 
        + "")
    public NCQueryResult setupAlarm(
        @Slot("my_time") List<NCToken> timeTokens,
        @Slot("my_time.NUM_FROM") List<Long> numValues,
        @Slot("my_time.UNIT_TYPE") List<ChronoUnit> numUnits,
        @Slot("my_time.DATE_FROM") List<Long> dateValues,
        NCConversationContext conversation,
        NCSentence sentence
    ) {
        
        // ... do something ...
        
        return NCQueryResult.text("...");
    }
}
```

**Comment by aradzinski** [comment]
I like the idea. Few comments:
1. How do we support multiple intents having the same callback?
2. Intent must have ID.
3. Keep in mind that TERM can be one or more different tokens (different for each sentence) - and therefore we can't have a specific method signature for it.

**Comment by aradzinski** [comment]
@skhdl Here's the method specification for `NCIntent`, `NCIntentRef` and `NCIntentTerm` annotations. The method should be:
- Method should have either `NCIntent` or `NCIntentRef` annotation but not both
- Method should return `NCQueryResult`
- 1st parameter should always be `NCIntentSolverContext` (no annotations is required)
- Only one (1st) parameter is mandatory, everything else is optional.
- All other optional parameters should have `NCIntentTerm` annotation (i.e. other parameters without this annotation are not allowed)
- Annotated parameter type can be: `NCToken` for term (1,1) quantifier, `Option[NCToken]` or `java.lang.Optional<NCToken>` for term (0,1) quantifier, or `List[NCToken]` or `java.util.List<NCToken>` for term (_, >1) quantifier.

Both `NCModel` and `NCModelProvider` should be scanned for annotated methods.
Multiple methods in each class can be annotated. They all (from both classes) should be added to the same solver.

**Comment by aradzinski** [comment]
For the record: here's final ANTLR4 grammar that is used for Intent DSL compilation:
```yaml
grammar NCIntentDsl;

intent: intentId convDecl? orderDecl? terms EOF;
intentId: 'id' EQ ID;
convDecl: 'conv' EQ BOOL;
orderDecl: 'order' EQ BOOL;
terms: term | terms term;
term: 'term' termId? EQ LCURLY item RCURLY minMax?;
termId: LPAREN ID RPAREN;
item
    : predicate
    | LPAREN item RPAREN
    | item AND item
    | item OR item
    | EXCL item
    ;
predicate
    : 'id' PRED_OP rvalue
    | 'parent' PRED_OP rvalue
    | 'group' PRED_OP rvalue
    | 'value' PRED_OP rvalue
    | meta PRED_OP rvalue
    ;
rvalue
    : 'null' 
    | BOOL
    | DEC_NUM
    | FLOAT_NUM
    | SQUOTE ~'\''* SQUOTE
    ;
minMax: minMaxShortcut | minMaxRange;
minMaxShortcut: PLUS | QUESTION | STAR;
minMaxRange: LBR INT COMMA INT RBR;
meta
    : TILDA ID
    | TILDA ID LBR INT RBR
    | TILDA ID LBR SQUOTE ~'\''+ SQUOTE RBR
    ;
PRED_OP: '==' | '!=' | '>=' | '<=' | '%%' | '!%' | '>' | '<' | '@@' | '!@' | '@#' | '!#' | '@$' | '!$';
AND: '&&';
OR: '||';
EXCL: '!';
LPAREN: '(';
RPAREN: ')';
LCURLY: '{';
RCURLY: '}';
SQUOTE: '\'';
TILDA: '~';
LBR: '[';
RBR: ']';
COMMA: ',';
COLON: ':';
MINUS: '-';
DOT: '.';
UNDERSCORE: '_';
EQ: '=';
PLUS: '+';
QUESTION: '?';
STAR: '*';
BOOL: 'true' | 'false';
INT: [0-9]+;
DEC_NUM: MINUS? INT;
FLOAT_NUM: MINUS? INT DOT INT;
ID: ([a-z]|[A-Z])+ ([a-z]|[A-Z]|[0-9]|COLON|MINUS|UNDERSCORE)*;
WS : [ \r\t\u000C\n]+ -> skip ;

ErrorCharacter
  : .
  ;
```

**Comment by aradzinski** [comment]
Here's the entire model source code for LightSwitch example:
```scala
package org.nlpcraft.examples.lightswitch

import org.nlpcraft.model._
import org.nlpcraft.model.intent.{NCIntent, NCIntentTerm, NCIntentSolverContext}
import org.nlpcraft.model.utils.NCTokenUtils._

class LightSwitchModel extends NCModelProviderAdapter {
    @NCIntent("id=act conv=false term(act)={id=='ls:act-on' || id=='ls:act-off'} term(loc)={id=='ls:loc'}*")
    def onMatch(ctx: NCIntentSolverContext,
        @NCIntentTerm("act") actTok: NCToken,
        @NCIntentTerm("loc") locToks: List[NCToken]): NCQueryResult = {
        val status = if (actTok.getId == "ls:act-on") "on" else "off"
        val location = if (locToks.isEmpty) "entire house" else locToks.map(getOriginalText).mkString(", ")
    
        NCQueryResult.text(s"Lights '$status' in '${location.toLowerCase}'.")
    }
    
    setup("org/nlpcraft/examples/lightswitch/lightswitch_model.yaml")
}
```
